### ISSUE TITLE
Add OpenAED to Taginfo Projects

### ISSUE THREAD

**Issue by danieldegroot2** [openaed/openaed#1]
Show the OpenStreetMap community what [data](https://wiki.openstreetmap.org/wiki/Tags) you are using. Add OpenAED to the [list](https://taginfo.openstreetmap.org/projects) of [Taginfo Projects](https://github.com/taginfo/taginfo-projects).

Example: [Open AED Map](https://taginfo.openstreetmap.org/projects/openaedmap#overview)

**Comment by jxpsert** [comment]
https://github.com/taginfo/taginfo-projects/pull/184
